hash-format = "sha256"

[[files]]
file = "config/featuredservers.json"

[[files]]
file = "mods/advancementinfo.pw.toml"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
metafile = true

[[files]]
file = "mods/big-pony.pw.toml"
metafile = true

[[files]]
file = "mods/bits-and-chisels.pw.toml"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
metafile = true

[[files]]
file = "mods/chisel-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emicompat.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
metafile = true

[[files]]
file = "mods/featuredserversfabric.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/hd-skins.pw.toml"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/midnightcontrols-extra.pw.toml"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
metafile = true

[[files]]
file = "mods/puddles.pw.toml"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
metafile = true

[[files]]
file = "mods/redstone-multimeter.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/slotlink.pw.toml"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/terrestria.pw.toml"
metafile = true

[[files]]
file = "mods/traverse.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/unicopia.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/wilder-wild.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true
